// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment6.com.bikeshop.server;

/************************************************************/
/**
 * 
 */
public class Add {
	/**
	 * 
	 */
	public Bike bike;

	/**
	 * 
	 */
	public void add() {
	}

	public Bike getBike() {
		return bike;
	}

	public void setBike(Bike bike) {
		this.bike = bike;
	}

	@Override
	public String toString() {
		return "Add [bike=" + bike + "]";
	}
	
	
}
