// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment6.com.bikeshop.server;

/************************************************************/
/**
 * 
 */
public class Add {
	/**
	 * 
	 */
	public Bike bike;

	/**
	 * 
	 */
	public void add() {
	}
}
