// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment6.com.bikeshop.server;

/************************************************************/
/**
 * 
 */
public class Authentication {
	/**
	 * 
	 */
	public Boolean isAuthorized;

	/**
	 * 
	 */
	public void authorize() {
	}

	public Boolean getIsAuthorized() {
		return isAuthorized;
	}

	public void setIsAuthorized(Boolean isAuthorized) {
		this.isAuthorized = isAuthorized;
	}

	@Override
	public String toString() {
		return "Authentication [isAuthorized=" + isAuthorized + "]";
	}
	
	
}
