// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment6.com.bikeshop.server;

/************************************************************/
/**
 * 
 */
public class Authentication {
	/**
	 * 
	 */
	public Boolean isAuthorized;

	/**
	 * 
	 */
	public void authorize() {
	}
}
