// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment6.com.bikeshop.server;

/************************************************************/
/**
 * 
 */
public class Bike {
	/**
	 * 
	 */
	public Long bikeId;
	/**
	 * 
	 */
	public Boolean isAvailable;
	/**
	 * 
	 */
	public Reservation reservation;
	/**
	 * 
	 */
	public Long updateBy;
	/**
	 * 
	 */
	public Long price;
	/**
	 * 
	 */
	public String description;

	/**
	 * 
	 */
	public void update() {
	}
}
