// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment6.com.bikeshop.server;

import Assignment6.com.bikeshop.client.Customer;

/************************************************************/
/**
 * 
 */
public class CustomerDb {
	/**
	 * 
	 */
	public Customer customer;
	/**
	 * 
	 */
	public Bike bike;

	/**
	 * 
	 */
	public void update() {
	}
}
