// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment6.com.bikeshop.server;

import Assignment6.com.bikeshop.client.Customer;

/************************************************************/
/**
 * 
 */
public class CustomerDb {
	/**
	 * 
	 */
	public Customer customer;
	/**
	 * 
	 */
	public Bike bike;

	/**
	 * 
	 */
	public void update() {
	}

	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Bike getBike() {
		return bike;
	}

	public void setBike(Bike bike) {
		this.bike = bike;
	}

	@Override
	public String toString() {
		return "CustomerDb [customer=" + customer + ", bike=" + bike + "]";
	}
	
	
}
