// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment6.com.bikeshop.server;

import Assignment6.com.bikeshop.client.Employee;

/************************************************************/
/**
 * 
 */
public class EmployeeDb {
	/**
	 * 
	 */
	public Employee employee;
	/**
	 * 
	 */
	public Bike bike;

	/**
	 * 
	 */
	public void update() {
	}

	public Employee getEmployee() {
		return employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Bike getBike() {
		return bike;
	}

	public void setBike(Bike bike) {
		this.bike = bike;
	}

	@Override
	public String toString() {
		return "EmployeeDb [employee=" + employee + ", bike=" + bike + "]";
	}
}