// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment6.com.bikeshop.server;

import Assignment6.com.bikeshop.client.Employee;

/************************************************************/
/**
 * 
 */
public class EmployeeDb {
	/**
	 * 
	 */
	public Employee employee;
	/**
	 * 
	 */
	public Bike bike;

	/**
	 * 
	 */
	public void update() {
	}
}
