// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment6.com.bikeshop.server;

/************************************************************/
/**
 * 
 */
public class Overwrite {
	/**
	 * 
	 */
	public Bike bike;

	/**
	 * 
	 */
	public void overwrite() {
	}

	public Bike getBike() {
		return bike;
	}

	public void setBike(Bike bike) {
		this.bike = bike;
	}

	@Override
	public String toString() {
		return "Overwrite [bike=" + bike + "]";
	}
}