// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment6.com.bikeshop.server;

/************************************************************/
/**
 * 
 */
public class Overwrite {
	/**
	 * 
	 */
	public Bike bike;

	/**
	 * 
	 */
	public void overwrite() {
	}
}
