// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment6.com.bikeshop.server;

/************************************************************/
/**
 * 
 */
public class Reservation {
	/**
	 * 
	 */
	public String reservationDate;
	/**
	 * 
	 */
	public Long bikeId;
	/**
	 * 
	 */
	public String startDate;
	/**
	 * 
	 */
	public String endDate;

	/**
	 * 
	 */
	public void reserve() {
	}

	public String getReservationDate() {
		return reservationDate;
	}

	public void setReservationDate(String reservationDate) {
		this.reservationDate = reservationDate;
	}

	public Long getBikeId() {
		return bikeId;
	}

	public void setBikeId(Long bikeId) {
		this.bikeId = bikeId;
	}

	public String getStartDate() {
		return startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public String getEndDate() {
		return endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	@Override
	public String toString() {
		return "Reservation [reservationDate=" + reservationDate + ", bikeId=" + bikeId + ", startDate=" + startDate
				+ ", endDate=" + endDate + "]";
	}
	
	
}
