// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment6.com.bikeshop.server;

/************************************************************/
/**
 * 
 */
public class Reservation {
	/**
	 * 
	 */
	public String reservationDate;
	/**
	 * 
	 */
	public Bike bikeId;
	/**
	 * 
	 */
	public String startDate;
	/**
	 * 
	 */
	public String endDate;

	/**
	 * 
	 */
	public void reserve() {
	}
}
