// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment6.com.bikeshop.client;

/************************************************************/
/**
 * 
 */
public class Customer {
	/**
	 * 
	 */
	public String customerName;
	/**
	 * 
	 */
	public Long customerId;
}
