// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment6.com.bikeshop.client;

/************************************************************/
/**
 * 
 */
public class Employee {
	/**
	 * 
	 */
	public String employeeName;
	/**
	 * 
	 */
	public Long employeeId;
	/**
	 * 
	 */
	public Boolean isManager;
	
	public String getEmployeeName() {
		return employeeName;
	}
	
	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}
	
	public Long getEmployeeId() {
		return employeeId;
	}
	
	public void setEmployeeId(Long employeeId) {
		this.employeeId = employeeId;
	}
	
	public Boolean getIsManager() {
		return isManager;
	}
	
	public void setIsManager(Boolean isManager) {
		this.isManager = isManager;
	}

	@Override
	public String toString() {
		return "Employee [employeeName=" + employeeName + ", employeeId=" + employeeId + ", isManager=" + isManager
				+ "]";
	}
	
}
